version: '3'
services:
    apache:
        container_name: tampico34.com
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ../:/var/www/html
        ports:
            - 8081:80